//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Content.text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BBDEVSYS.Content.text.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCRUED_ITEM_NO.
        /// </summary>
        public static string ACCRUED_ITEM_NO {
            get {
                return ResourceManager.GetString("ACCRUED_ITEM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string ACCRUED_MONTH {
            get {
                return ResourceManager.GetString("ACCRUED_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCRUED_NO.
        /// </summary>
        public static string ACCRUED_NO {
            get {
                return ResourceManager.GetString("ACCRUED_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string ACCRUED_YEAR {
            get {
                return ResourceManager.GetString("ACCRUED_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำอธิบาย.
        /// </summary>
        public static string ACEDesc {
            get {
                return ResourceManager.GetString("ACEDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสิทธิ์.
        /// </summary>
        public static string ACRName {
            get {
                return ResourceManager.GetString("ACRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Amount.
        /// </summary>
        public static string ACTUAL_AMOUNT {
            get {
                return ResourceManager.GetString("ACTUAL_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AMOUNT {
            get {
                return ResourceManager.GetString("AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดสิทธิ์.
        /// </summary>
        public static string AssignUserRole {
            get {
                return ResourceManager.GetString("AssignUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดรายเซ็นต์.
        /// </summary>
        public static string AssignUserRoleLicense {
            get {
                return ResourceManager.GetString("AssignUserRoleLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังตรวจสอบ.
        /// </summary>
        public static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล.
        /// </summary>
        public static string BoxData {
            get {
                return ResourceManager.GetString("BoxData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียด.
        /// </summary>
        public static string BoxDetail {
            get {
                return ResourceManager.GetString("BoxDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอด (ยกไป).
        /// </summary>
        public static string Bring {
            get {
                return ResourceManager.GetString("Bring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกไฟล์.
        /// </summary>
        public static string BrowseFile {
            get {
                return ResourceManager.GetString("BrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        public static string BUSINESS_UNIT {
            get {
                return ResourceManager.GetString("BUSINESS_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รับทราบ.
        /// </summary>
        public static string ButtonAcknowledge {
            get {
                return ResourceManager.GetString("ButtonAcknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มเอกสาร.
        /// </summary>
        public static string ButtonAddAttachment {
            get {
                return ResourceManager.GetString("ButtonAddAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่ม.
        /// </summary>
        public static string ButtonAddItem {
            get {
                return ResourceManager.GetString("ButtonAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันข้อมูล.
        /// </summary>
        public static string ButtonAgentConfirmData {
            get {
                return ResourceManager.GetString("ButtonAgentConfirmData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกเหตุการณ์.
        /// </summary>
        public static string ButtonAgentEvent {
            get {
                return ResourceManager.GetString("ButtonAgentEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติ.
        /// </summary>
        public static string ButtonApprove {
            get {
                return ResourceManager.GetString("ButtonApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนกลับ.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลับสู่หน้า Inbox.
        /// </summary>
        public static string ButtonBackToInbox {
            get {
                return ResourceManager.GetString("ButtonBackToInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขา.
        /// </summary>
        public static string ButtonBranch {
            get {
                return ResourceManager.GetString("ButtonBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรียกดู.
        /// </summary>
        public static string ButtonBrowse {
            get {
                return ResourceManager.GetString("ButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกคำขอ.
        /// </summary>
        public static string ButtonCancelRequest {
            get {
                return ResourceManager.GetString("ButtonCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกเอกสาร SAP.
        /// </summary>
        public static string ButtonCancelSAPDoc {
            get {
                return ResourceManager.GetString("ButtonCancelSAPDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบเงิน.
        /// </summary>
        public static string ButtonCheckAmount {
            get {
                return ResourceManager.GetString("ButtonCheckAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปิด.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปิดหน้าต่าง.
        /// </summary>
        public static string ButtonClosePopup {
            get {
                return ResourceManager.GetString("ButtonClosePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เสร็จสิ้น.
        /// </summary>
        public static string ButtonComplete {
            get {
                return ResourceManager.GetString("ButtonComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งข้อมูล.
        /// </summary>
        public static string ButtonCompleteMenu03 {
            get {
                return ResourceManager.GetString("ButtonCompleteMenu03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยัน.
        /// </summary>
        public static string ButtonConfirm {
            get {
                return ResourceManager.GetString("ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คัดลอก.
        /// </summary>
        public static string ButtonCopy {
            get {
                return ResourceManager.GetString("ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างใหม่.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างแผนงาน.
        /// </summary>
        public static string ButtonCreateBudgetPlan {
            get {
                return ResourceManager.GetString("ButtonCreateBudgetPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างใหม่.
        /// </summary>
        public static string ButtonCreateBudgetPlanActivity {
            get {
                return ResourceManager.GetString("ButtonCreateBudgetPlanActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างแผนงานย่อย.
        /// </summary>
        public static string ButtonCreateBudgetSubPlan {
            get {
                return ResourceManager.GetString("ButtonCreateBudgetSubPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างเอกสาร SAP.
        /// </summary>
        public static string ButtonCreateSAPDoc {
            get {
                return ResourceManager.GetString("ButtonCreateSAPDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบิก.
        /// </summary>
        public static string ButtonDeduct {
            get {
                return ResourceManager.GetString("ButtonDeduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดผลิตภัณฑ์.
        /// </summary>
        public static string ButtonDefineProduct {
            get {
                return ResourceManager.GetString("ButtonDefineProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ทำหน้าที่แทน.
        /// </summary>
        public static string ButtonDelegate {
            get {
                return ResourceManager.GetString("ButtonDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบ.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดง.
        /// </summary>
        public static string ButtonDisplay {
            get {
                return ResourceManager.GetString("ButtonDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลด.
        /// </summary>
        public static string ButtonDownload {
            get {
                return ResourceManager.GetString("ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกกลุ่ม.
        /// </summary>
        public static string ButtonDropdownBudgetPlanActivity {
            get {
                return ResourceManager.GetString("ButtonDropdownBudgetPlanActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไข.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำจ่าย.
        /// </summary>
        public static string ButtonEditInvoice {
            get {
                return ResourceManager.GetString("ButtonEditInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งอีเมล.
        /// </summary>
        public static string ButtonEmail {
            get {
                return ResourceManager.GetString("ButtonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเมิน.
        /// </summary>
        public static string ButtonEvaluate {
            get {
                return ResourceManager.GetString("ButtonEvaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผลการประเมิน.
        /// </summary>
        public static string ButtonEvaResultScore {
            get {
                return ResourceManager.GetString("ButtonEvaResultScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุยอดขาย.
        /// </summary>
        public static string ButtonFillSales {
            get {
                return ResourceManager.GetString("ButtonFillSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดูแบบฟอร์ม.
        /// </summary>
        public static string ButtonForm {
            get {
                return ResourceManager.GetString("ButtonForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประวัติ.
        /// </summary>
        public static string ButtonHistory {
            get {
                return ResourceManager.GetString("ButtonHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate ข้อมูล.
        /// </summary>
        public static string ButtonIntegrate {
            get {
                return ResourceManager.GetString("ButtonIntegrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าสู่ระบบ.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกจากระบบ.
        /// </summary>
        public static string ButtonLogout {
            get {
                return ResourceManager.GetString("ButtonLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จัดการ.
        /// </summary>
        public static string ButtonManage {
            get {
                return ResourceManager.GetString("ButtonManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping ข้อมูล.
        /// </summary>
        public static string ButtonMapping {
            get {
                return ResourceManager.GetString("ButtonMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตกลง.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปิด.
        /// </summary>
        public static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ช่วงเวลาประเมิน.
        /// </summary>
        public static string ButtonPeriod {
            get {
                return ResourceManager.GetString("ButtonPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้าง.
        /// </summary>
        public static string ButtonPeriodCreate {
            get {
                return ResourceManager.GetString("ButtonPeriodCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview ข้อมูล.
        /// </summary>
        public static string ButtonPreview {
            get {
                return ResourceManager.GetString("ButtonPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์บันทึก.
        /// </summary>
        public static string ButtonPrintMemo {
            get {
                return ResourceManager.GetString("ButtonPrintMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประมวลผลข้อมูล.
        /// </summary>
        public static string ButtonProcess {
            get {
                return ResourceManager.GetString("ButtonProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รับเอกสาร.
        /// </summary>
        public static string ButtonReceive {
            get {
                return ResourceManager.GetString("ButtonReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่อนุมัติ.
        /// </summary>
        public static string ButtonReject {
            get {
                return ResourceManager.GetString("ButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงรายงาน.
        /// </summary>
        public static string ButtonReportDisplay {
            get {
                return ResourceManager.GetString("ButtonReportDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งอนุมัติ.
        /// </summary>
        public static string ButtonRequest {
            get {
                return ResourceManager.GetString("ButtonRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งอนุมัติ.
        /// </summary>
        public static string ButtonResendRequest {
            get {
                return ResourceManager.GetString("ButtonResendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกข้อมูล.
        /// </summary>
        public static string ButtonRespondent {
            get {
                return ResourceManager.GetString("ButtonRespondent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งข้อมูล.
        /// </summary>
        public static string ButtonSAPSendData {
            get {
                return ResourceManager.GetString("ButtonSAPSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทดสอบ.
        /// </summary>
        public static string ButtonSAPTest {
            get {
                return ResourceManager.GetString("ButtonSAPTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึก.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกสาขา.
        /// </summary>
        public static string ButtonSelectBranch {
            get {
                return ResourceManager.GetString("ButtonSelectBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกใบจัดซื้อ.
        /// </summary>
        public static string ButtonSelectPR {
            get {
                return ResourceManager.GetString("ButtonSelectPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกใบขออนุมัติสั่งจ่าย.
        /// </summary>
        public static string ButtonSelectPRQPRAToSAP {
            get {
                return ResourceManager.GetString("ButtonSelectPRQPRAToSAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งผลการประเมิน.
        /// </summary>
        public static string ButtonSendEva {
            get {
                return ResourceManager.GetString("ButtonSendEva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การใช้งบ.
        /// </summary>
        public static string ButtonStatement {
            get {
                return ResourceManager.GetString("ButtonStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรียกดู.
        /// </summary>
        public static string ButtonTask {
            get {
                return ResourceManager.GetString("ButtonTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรียกคืน.
        /// </summary>
        public static string ButtonUndo {
            get {
                return ResourceManager.GetString("ButtonUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ข้อมูล.
        /// </summary>
        public static string ButtonUpload {
            get {
                return ResourceManager.GetString("ButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบ.
        /// </summary>
        public static string ButtonValidate {
            get {
                return ResourceManager.GetString("ButtonValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCT_CODE.
        /// </summary>
        public static string CCT_CODE {
            get {
                return ResourceManager.GetString("CCT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string CHANNELS {
            get {
                return ResourceManager.GetString("CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        public static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัส.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string COMPANY_CODE {
            get {
                return ResourceManager.GetString("COMPANY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริษัท.
        /// </summary>
        public static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Payment.
        /// </summary>
        public static string CONDITION_PYM {
            get {
                return ResourceManager.GetString("CONDITION_PYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string CostCenter {
            get {
                return ResourceManager.GetString("CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CURRENCY {
            get {
                return ResourceManager.GetString("CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบรูป.
        /// </summary>
        public static string DeletePhoto {
            get {
                return ResourceManager.GetString("DeletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string DISCOUNT {
            get {
                return ResourceManager.GetString("DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string DURATION {
            get {
                return ResourceManager.GetString("DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        public static string EDITION {
            get {
                return ResourceManager.GetString("EDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูล.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Payment Date.
        /// </summary>
        public static string EndPaymentDate {
            get {
                return ResourceManager.GetString("EndPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เมนู.
        /// </summary>
        public static string EvaMenu {
            get {
                return ResourceManager.GetString("EvaMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string FEE {
            get {
                return ResourceManager.GetString("FEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Type.
        /// </summary>
        public static string FEE_TYPE {
            get {
                return ResourceManager.GetString("FEE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อไฟล์.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FirstnameEN {
            get {
                return ResourceManager.GetString("FirstnameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string FirstnameTH {
            get {
                return ResourceManager.GetString("FirstnameTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund.
        /// </summary>
        public static string FUND {
            get {
                return ResourceManager.GetString("FUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Account.
        /// </summary>
        public static string GLAccount {
            get {
                return ResourceManager.GetString("GLAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount (Include VAT).
        /// </summary>
        public static string INCLUDE_VAT_AMOUNT {
            get {
                return ResourceManager.GetString("INCLUDE_VAT_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Amount.
        /// </summary>
        public static string INV_AMOUNT {
            get {
                return ResourceManager.GetString("INV_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved by.
        /// </summary>
        public static string INV_APPROVED_BY {
            get {
                return ResourceManager.GetString("INV_APPROVED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        public static string INV_APPROVED_DATE {
            get {
                return ResourceManager.GetString("INV_APPROVED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inv. Due Date.
        /// </summary>
        public static string INV_DUE_DATE {
            get {
                return ResourceManager.GetString("INV_DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No..
        /// </summary>
        public static string INV_ITEM_NO {
            get {
                return ResourceManager.GetString("INV_ITEM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string INV_MONTH {
            get {
                return ResourceManager.GetString("INV_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month From.
        /// </summary>
        public static string INV_MONTH_FROM {
            get {
                return ResourceManager.GetString("INV_MONTH_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month To.
        /// </summary>
        public static string INV_MONTH_TO {
            get {
                return ResourceManager.GetString("INV_MONTH_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        public static string INV_NO {
            get {
                return ResourceManager.GetString("INV_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive by.
        /// </summary>
        public static string INV_REC_BY {
            get {
                return ResourceManager.GetString("INV_REC_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        public static string INV_REC_DATE {
            get {
                return ResourceManager.GetString("INV_REC_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string INV_YEAR {
            get {
                return ResourceManager.GetString("INV_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year From.
        /// </summary>
        public static string INV_YEAR_FROM {
            get {
                return ResourceManager.GetString("INV_YEAR_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaer To.
        /// </summary>
        public static string INV_YEAR_TO {
            get {
                return ResourceManager.GetString("INV_YEAR_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการ.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust and Refund.
        /// </summary>
        public static string MenuAdjAndRfd {
            get {
                return ResourceManager.GetString("MenuAdjAndRfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จัดการสิทธิ์การใช้งานระบบ.
        /// </summary>
        public static string MenuAppCompositeRole {
            get {
                return ResourceManager.GetString("MenuAppCompositeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดสิทธิ์ผู้ใช้งาน.
        /// </summary>
        public static string MenuAssignUserRole {
            get {
                return ResourceManager.GetString("MenuAssignUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดสิทธิ์การใช้งาน.
        /// </summary>
        public static string MenuAuthorization {
            get {
                return ResourceManager.GetString("MenuAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเมินตัวแทน/แบบสอบถาม.
        /// </summary>
        public static string MenuCAEvaAndQuestionaire {
            get {
                return ResourceManager.GetString("MenuCAEvaAndQuestionaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลส่วนกลาง.
        /// </summary>
        public static string MenuCenterSetting {
            get {
                return ResourceManager.GetString("MenuCenterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เดือน.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        public static string NET_AMOUNT {
            get {
                return ResourceManager.GetString("NET_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Charge Amount(Wht).
        /// </summary>
        public static string NET_CHARGE_AMOUNT {
            get {
                return ResourceManager.GetString("NET_CHARGE_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Code.
        /// </summary>
        public static string PAYMENT_ITEMS_CODE {
            get {
                return ResourceManager.GetString("PAYMENT_ITEMS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Item.
        /// </summary>
        public static string PAYMENT_ITEMS_FEE_ITEM {
            get {
                return ResourceManager.GetString("PAYMENT_ITEMS_FEE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Name.
        /// </summary>
        public static string PAYMENT_ITEMS_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_ITEMS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period of.
        /// </summary>
        public static string PERIOD_ACCRUED {
            get {
                return ResourceManager.GetString("PERIOD_ACCRUED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Month.
        /// </summary>
        public static string PERIOD_MONTH {
            get {
                return ResourceManager.GetString("PERIOD_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Year.
        /// </summary>
        public static string PERIOD_YEAR {
            get {
                return ResourceManager.GetString("PERIOD_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Due Date.
        /// </summary>
        public static string PODueDate {
            get {
                return ResourceManager.GetString("PODueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการปิดข้อตกลงทางการค้าหรือไม่?.
        /// </summary>
        public static string PopupCloseProposalBody {
            get {
                return ResourceManager.GetString("PopupCloseProposalBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการปิดข้อตกลงทางการค้า.
        /// </summary>
        public static string PopupCloseProposalHeader {
            get {
                return ResourceManager.GetString("PopupCloseProposalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการรับทราบข้อมูลหรือไม่?.
        /// </summary>
        public static string PopupConfirmAcKnowLedgeBody {
            get {
                return ResourceManager.GetString("PopupConfirmAcKnowLedgeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการรับทราบ.
        /// </summary>
        public static string PopupConfirmAcKnowLedgeHeader {
            get {
                return ResourceManager.GetString("PopupConfirmAcKnowLedgeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันข้อมูล {0} หรือไม่?.
        /// </summary>
        public static string PopupConfirmAgentDataBody {
            get {
                return ResourceManager.GetString("PopupConfirmAgentDataBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันข้อมูล.
        /// </summary>
        public static string PopupConfirmAgentDataHeader {
            get {
                return ResourceManager.GetString("PopupConfirmAgentDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการสร้างเหตุการณ์ของตัวแทนจำหน่ายหรือไม่?.
        /// </summary>
        public static string PopupConfirmAgentEventBody {
            get {
                return ResourceManager.GetString("PopupConfirmAgentEventBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการสร้างเหตุการณ์ของตัวแทนจำหน่าย.
        /// </summary>
        public static string PopupConfirmAgentEventHeader {
            get {
                return ResourceManager.GetString("PopupConfirmAgentEventHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการอนุมัติหรือไม่?.
        /// </summary>
        public static string PopupConfirmApproveBody {
            get {
                return ResourceManager.GetString("PopupConfirmApproveBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการอนุมัติ.
        /// </summary>
        public static string PopupConfirmApproveHeader {
            get {
                return ResourceManager.GetString("PopupConfirmApproveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลที่ทำการเปลี่ยนแปลงจะไม่ถูกบันทึก ยืนยันการย้อนกลับหรือไม่?.
        /// </summary>
        public static string PopupConfirmBackBody {
            get {
                return ResourceManager.GetString("PopupConfirmBackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการย้อนกลับ.
        /// </summary>
        public static string PopupConfirmBackHeader {
            get {
                return ResourceManager.GetString("PopupConfirmBackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการยกเลิกใบขออนุมัติ Job หรือไม่?.
        /// </summary>
        public static string PopupConfirmCancelJobBody {
            get {
                return ResourceManager.GetString("PopupConfirmCancelJobBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการยกเลิกใบขออนุมัติ Job.
        /// </summary>
        public static string PopupConfirmCancelJobHeader {
            get {
                return ResourceManager.GetString("PopupConfirmCancelJobHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการยกเลิกใบขออนุมัติจัดซื้อหรือไม่?.
        /// </summary>
        public static string PopupConfirmCancelPRBody {
            get {
                return ResourceManager.GetString("PopupConfirmCancelPRBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการยกเลืกใบขออนุมัติจัดซื้อ.
        /// </summary>
        public static string PopupConfirmCancelPRHeader {
            get {
                return ResourceManager.GetString("PopupConfirmCancelPRHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งข้อมูลไปยัง SAP หรือไม่?.
        /// </summary>
        public static string PopupConfirmConfirmToSAPBody {
            get {
                return ResourceManager.GetString("PopupConfirmConfirmToSAPBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งข้อมูล.
        /// </summary>
        public static string PopupConfirmConfirmToSAPHeader {
            get {
                return ResourceManager.GetString("PopupConfirmConfirmToSAPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการเบิกข้อมูลหรือไม่?.
        /// </summary>
        public static string PopupConfirmDeductBody {
            get {
                return ResourceManager.GetString("PopupConfirmDeductBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการเบิก.
        /// </summary>
        public static string PopupConfirmDeductHeader {
            get {
                return ResourceManager.GetString("PopupConfirmDeductHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการลบข้อมูลหรือไม่?.
        /// </summary>
        public static string PopupConfirmDeleteBody {
            get {
                return ResourceManager.GetString("PopupConfirmDeleteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการลบข้อมูล.
        /// </summary>
        public static string PopupConfirmDeleteHeader {
            get {
                return ResourceManager.GetString("PopupConfirmDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันเสร็จสิ้นการประเมินหรือไม่? หลังจากยืนยันจะไม่สามารถแก้ไขผลการประเมินได้อีก.
        /// </summary>
        public static string PopupConfirmFinishEvaBody {
            get {
                return ResourceManager.GetString("PopupConfirmFinishEvaBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันเสร็จสิ้นการประเมิน.
        /// </summary>
        public static string PopupConfirmFinishEvaHeader {
            get {
                return ResourceManager.GetString("PopupConfirmFinishEvaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันเสร็จสิ้นการกรอกแบบสอบถามหรือไม่? หลังจากยืนยันจะไม่สามารถแก้ไขแบบสอบถามได้อีก.
        /// </summary>
        public static string PopupConfirmFinishQuestionBody {
            get {
                return ResourceManager.GetString("PopupConfirmFinishQuestionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันเสร็จสิ้นการกรอกแบบสอบถาม.
        /// </summary>
        public static string PopupConfirmFinishQuestionHeader {
            get {
                return ResourceManager.GetString("PopupConfirmFinishQuestionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีการเปลี่ยนแปลงราคาสินค้าในช่วงเวลาที่เลือกใหม่ ยืนยันการเปลี่ยนนี้หรือไม่.
        /// </summary>
        public static string PopupConfirmPeriodChangeBody {
            get {
                return ResourceManager.GetString("PopupConfirmPeriodChangeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องการพิมพ์บันทึกหรือไม่?.
        /// </summary>
        public static string PopupConfirmPrintMemoBody {
            get {
                return ResourceManager.GetString("PopupConfirmPrintMemoBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการพิมพ์บันทึก.
        /// </summary>
        public static string PopupConfirmPrintMemoHeader {
            get {
                return ResourceManager.GetString("PopupConfirmPrintMemoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งข้อตกลงทางการค้าหรือไม่?.
        /// </summary>
        public static string PopupConfirmProposalBody {
            get {
                return ResourceManager.GetString("PopupConfirmProposalBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันข้อตกลงทางการค้า.
        /// </summary>
        public static string PopupConfirmProposalHeader {
            get {
                return ResourceManager.GetString("PopupConfirmProposalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการรับเอกสารหรือไม่?.
        /// </summary>
        public static string PopupConfirmReceiveBody {
            get {
                return ResourceManager.GetString("PopupConfirmReceiveBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการรับเอกสาร.
        /// </summary>
        public static string PopupConfirmReceiveHeader {
            get {
                return ResourceManager.GetString("PopupConfirmReceiveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการปฏิเสธหรือไม่?.
        /// </summary>
        public static string PopupConfirmRejectBody {
            get {
                return ResourceManager.GetString("PopupConfirmRejectBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการปฏิเสธ.
        /// </summary>
        public static string PopupConfirmRejectHeader {
            get {
                return ResourceManager.GetString("PopupConfirmRejectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการบันทึกข้อมูลหรือไม่?.
        /// </summary>
        public static string PopupConfirmSaveBody {
            get {
                return ResourceManager.GetString("PopupConfirmSaveBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการบันทึกข้อมูล.
        /// </summary>
        public static string PopupConfirmSaveHeader {
            get {
                return ResourceManager.GetString("PopupConfirmSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งผลการโอนงบประมาณภายในหรือไม่ ?.
        /// </summary>
        public static string PopupConfirmSendBudgetIntTransferBody {
            get {
                return ResourceManager.GetString("PopupConfirmSendBudgetIntTransferBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งผลการโอนงบประมาณภายใน.
        /// </summary>
        public static string PopupConfirmSendBudgetIntTransferHeader {
            get {
                return ResourceManager.GetString("PopupConfirmSendBudgetIntTransferHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งอีเมลหรือไม่?.
        /// </summary>
        public static string PopupConfirmSendEmailBody {
            get {
                return ResourceManager.GetString("PopupConfirmSendEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งอีเมล.
        /// </summary>
        public static string PopupConfirmSendEmailHeader {
            get {
                return ResourceManager.GetString("PopupConfirmSendEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันส่งผลการประเมินหรือไม่? หลังจากยืนยันจะไม่สามารถแก้ไขผลการประเมินได้อีก.
        /// </summary>
        public static string PopupConfirmSendEvaBody {
            get {
                return ResourceManager.GetString("PopupConfirmSendEvaBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันส่งผลการประเมิน.
        /// </summary>
        public static string PopupConfirmSendEvaHeader {
            get {
                return ResourceManager.GetString("PopupConfirmSendEvaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันส่งผลการประเมิน CA หรือไม่?.
        /// </summary>
        public static string PopupConfirmSendFormCASummaryBody {
            get {
                return ResourceManager.GetString("PopupConfirmSendFormCASummaryBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งผลการประเมิน CA.
        /// </summary>
        public static string PopupConfirmSendFormCASummaryHeader {
            get {
                return ResourceManager.GetString("PopupConfirmSendFormCASummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันส่งใบขออนุมัติ IOU หรือไม่?.
        /// </summary>
        public static string PopupConfirmSendIOUBody {
            get {
                return ResourceManager.GetString("PopupConfirmSendIOUBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งอนุมัติ.
        /// </summary>
        public static string PopupConfirmSendIOUHeader {
            get {
                return ResourceManager.GetString("PopupConfirmSendIOUHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันส่งใบขออนุมัติ Job หรือไม่?.
        /// </summary>
        public static string PopupConfirmSendJobBody {
            get {
                return ResourceManager.GetString("PopupConfirmSendJobBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันส่งใบขออนุมัติ Job.
        /// </summary>
        public static string PopupConfirmSendJobHeader {
            get {
                return ResourceManager.GetString("PopupConfirmSendJobHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันส่งใบขออนุมัติ ขอเบิกวัสดุ หรือไม่?.
        /// </summary>
        public static string PopupConfirmSendMaterialRequestBody {
            get {
                return ResourceManager.GetString("PopupConfirmSendMaterialRequestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งใบปะหน้าคำขออนุมัติจ่ายชดเชยคืนตัวแทน?.
        /// </summary>
        public static string PopupConfirmSendPRAGroupBody {
            get {
                return ResourceManager.GetString("PopupConfirmSendPRAGroupBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งใบปะหน้าคำขออนุมัติจ่ายชดเชยคืนตัวแทน.
        /// </summary>
        public static string PopupConfirmSendPRAGroupHeader {
            get {
                return ResourceManager.GetString("PopupConfirmSendPRAGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งใบขออนุมัติจัดซื้อหรือไม่?.
        /// </summary>
        public static string PopupConfirmSendPRBody {
            get {
                return ResourceManager.GetString("PopupConfirmSendPRBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งใบขออนุมัติจัดซื้อ.
        /// </summary>
        public static string PopupConfirmSendPRHeader {
            get {
                return ResourceManager.GetString("PopupConfirmSendPRHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันส่งใบขออนุมัติ Trade หรือไม่?.
        /// </summary>
        public static string PopupConfirmSendTradeBody {
            get {
                return ResourceManager.GetString("PopupConfirmSendTradeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันส่งใบขออนุมัติ Trade.
        /// </summary>
        public static string PopupConfirmSendTradeHeader {
            get {
                return ResourceManager.GetString("PopupConfirmSendTradeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการทดสอบส่งข้อมูลไปยัง SAP หรือไม่?.
        /// </summary>
        public static string PopupConfirmTestToSAPBody {
            get {
                return ResourceManager.GetString("PopupConfirmTestToSAPBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการทดสอบส่งข้อมูล.
        /// </summary>
        public static string PopupConfirmTestToSAPHeader {
            get {
                return ResourceManager.GetString("PopupConfirmTestToSAPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการเรียกคืนหรือไม่?.
        /// </summary>
        public static string PopupConfirmUndoBody {
            get {
                return ResourceManager.GetString("PopupConfirmUndoBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการเรียกคืน.
        /// </summary>
        public static string PopupConfirmUndoHeader {
            get {
                return ResourceManager.GetString("PopupConfirmUndoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการ Upload ข้อมูลหรือไม่?.
        /// </summary>
        public static string PopupConfirmUploadJobBody {
            get {
                return ResourceManager.GetString("PopupConfirmUploadJobBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการ Upload ข้อมูล.
        /// </summary>
        public static string PopupConfirmUploadJobHeader {
            get {
                return ResourceManager.GetString("PopupConfirmUploadJobHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการตรวจสอบข้อมูลหรือไม่?.
        /// </summary>
        public static string PopupConfirmValidateBody {
            get {
                return ResourceManager.GetString("PopupConfirmValidateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการตรวจสอบข้อมูล.
        /// </summary>
        public static string PopupConfirmValidateHeader {
            get {
                return ResourceManager.GetString("PopupConfirmValidateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดสินค้า.
        /// </summary>
        public static string PopupDefineProduct {
            get {
                return ResourceManager.GetString("PopupDefineProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีข้อผิดพลาด.
        /// </summary>
        public static string PopupErrorHeader {
            get {
                return ResourceManager.GetString("PopupErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string PopupInfoHeader {
            get {
                return ResourceManager.GetString("PopupInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดขายที่เกิดขึ้นจริงมีการเปลี่ยน กรุณาประมวลผลข้อมูลข้อตกลงทางการค้าใหม่.
        /// </summary>
        public static string PopupPleaseReProcessProposalBody {
            get {
                return ResourceManager.GetString("PopupPleaseReProcessProposalBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แจ้งเตือน.
        /// </summary>
        public static string PopupPleaseReProcessProposalHeader {
            get {
                return ResourceManager.GetString("PopupPleaseReProcessProposalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกรายการใบจัดซื้อ.
        /// </summary>
        public static string PopupPR {
            get {
                return ResourceManager.GetString("PopupPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกรายการใบสั่งจ่าย.
        /// </summary>
        public static string PopupPRQPRA {
            get {
                return ResourceManager.GetString("PopupPRQPRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งข้อมูลไปยัง SAP หรือไม่?.
        /// </summary>
        public static string PopupSAPCommitBody {
            get {
                return ResourceManager.GetString("PopupSAPCommitBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งข้อมูลไปยัง SAP.
        /// </summary>
        public static string PopupSAPCommitHeader {
            get {
                return ResourceManager.GetString("PopupSAPCommitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเร็จ.
        /// </summary>
        public static string PopupSuccessHeader {
            get {
                return ResourceManager.GetString("PopupSuccessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface ใบสั่งจ่ายไปยังระบบ SAP.
        /// </summary>
        public static string PopupSuccessPRQPRAToSAPHeader {
            get {
                return ResourceManager.GetString("PopupSuccessPRQPRAToSAPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทดสอบ Interface ใบสั่งจ่ายไปยังระบบ SAP.
        /// </summary>
        public static string PopupSuccessTestPRQPRAToSAPHeader {
            get {
                return ResourceManager.GetString("PopupSuccessTestPRQPRAToSAPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดตรวจสอบข้อมูลอีกครั้ง.
        /// </summary>
        public static string PopupWarningProductConfigHeader {
            get {
                return ResourceManager.GetString("PopupWarningProductConfigHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO Due Date.
        /// </summary>
        public static string PRO_DUE_DATE {
            get {
                return ResourceManager.GetString("PRO_DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO No..
        /// </summary>
        public static string PRO_NO {
            get {
                return ResourceManager.GetString("PRO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO Create Date.
        /// </summary>
        public static string PRO_REC_DATE {
            get {
                return ResourceManager.GetString("PRO_REC_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Amount.
        /// </summary>
        public static string RATE_AMT {
            get {
                return ResourceManager.GetString("RATE_AMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Transaction.
        /// </summary>
        public static string RATE_TRANS {
            get {
                return ResourceManager.GetString("RATE_TRANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รับ.
        /// </summary>
        public static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string REMARK {
            get {
                return ResourceManager.GetString("REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        public static string REPORT_TYPE {
            get {
                return ResourceManager.GetString("REPORT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงข้อมูล.
        /// </summary>
        public static string RoleDisplay {
            get {
                return ResourceManager.GetString("RoleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จัดการข้อมูล.
        /// </summary>
        public static string RoleManage {
            get {
                return ResourceManager.GetString("RoleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No..
        /// </summary>
        public static string SEQUENCE {
            get {
                return ResourceManager.GetString("SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Payment Date.
        /// </summary>
        public static string StartPaymentDate {
            get {
                return ResourceManager.GetString("StartPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติคำขอเรียบร้อย.
        /// </summary>
        public static string SuccessfulApprove {
            get {
                return ResourceManager.GetString("SuccessfulApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกคำขอเรียบร้อย.
        /// </summary>
        public static string SuccessfulCancelRequest {
            get {
                return ResourceManager.GetString("SuccessfulCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการจ่ายเรียบร้อย.
        /// </summary>
        public static string SuccessfulCloseInvoice {
            get {
                return ResourceManager.GetString("SuccessfulCloseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบข้อมูลเรียบร้อย.
        /// </summary>
        public static string SuccessfulDelete {
            get {
                return ResourceManager.GetString("SuccessfulDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูลเรียบร้อย.
        /// </summary>
        public static string SuccessfulEdit {
            get {
                return ResourceManager.GetString("SuccessfulEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัดสต๊อกวัสดุเรียบร้อย.
        /// </summary>
        public static string SuccessfulMaterialDeduction {
            get {
                return ResourceManager.GetString("SuccessfulMaterialDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดำเนินการเรียบร้อย.
        /// </summary>
        public static string SuccessfulProceed {
            get {
                return ResourceManager.GetString("SuccessfulProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface ใบสั่งจ่ายไปยังระบบ SAP เสร็จสิ้น.
        /// </summary>
        public static string SuccessfulPRQPRAToSAPSave {
            get {
                return ResourceManager.GetString("SuccessfulPRQPRAToSAPSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกใบขออนุมัติจัดซื้อเรียบร้อย.
        /// </summary>
        public static string SuccessfulPRToSAPCancel {
            get {
                return ResourceManager.GetString("SuccessfulPRToSAPCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface ใบขออนุมัติจัดซื้อไปยังระบบ SAP เสร็จสิ้น.
        /// </summary>
        public static string SuccessfulPRToSAPSave {
            get {
                return ResourceManager.GetString("SuccessfulPRToSAPSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปฏิเสธคำขอเรียบร้อย.
        /// </summary>
        public static string SuccessfulReject {
            get {
                return ResourceManager.GetString("SuccessfulReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งคำขอเรียบร้อย.
        /// </summary>
        public static string SuccessfulResendRequest {
            get {
                return ResourceManager.GetString("SuccessfulResendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลเรียบร้อย.
        /// </summary>
        public static string SuccessfulSave {
            get {
                return ResourceManager.GetString("SuccessfulSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งคำขอเรียบร้อย.
        /// </summary>
        public static string SuccessfulSendRequest {
            get {
                return ResourceManager.GetString("SuccessfulSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกใบขออนุมัติจัดซื้อเรียบร้อย.
        /// </summary>
        public static string SuccessfulTestPRoSAPCancel {
            get {
                return ResourceManager.GetString("SuccessfulTestPRoSAPCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผ่านการทดสอบ.
        /// </summary>
        public static string SuccessfulTestPRoSAPSave {
            get {
                return ResourceManager.GetString("SuccessfulTestPRoSAPSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผ่านการทดสอบ.
        /// </summary>
        public static string SuccessfulTestPRQPRAToSAPSave {
            get {
                return ResourceManager.GetString("SuccessfulTestPRQPRAToSAPSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ข้อมูลเรียบร้อย.
        /// </summary>
        public static string SuccessfulUpload {
            get {
                return ResourceManager.GetString("SuccessfulUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลถูกต้องสามารถ Upload ข้อมูลได้.
        /// </summary>
        public static string SuccessfulUploadValidate {
            get {
                return ResourceManager.GetString("SuccessfulUploadValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบข้อมูลเรียบร้อย.
        /// </summary>
        public static string SuccessfulValid {
            get {
                return ResourceManager.GetString("SuccessfulValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผ่านการตรวจสอบ.
        /// </summary>
        public static string SuccessfulVerify {
            get {
                return ResourceManager.GetString("SuccessfulVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผ่านการตรวจสอบ.
        /// </summary>
        public static string SuccessfulVerify1 {
            get {
                return ResourceManager.GetString("SuccessfulVerify1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Amount.
        /// </summary>
        public static string SUM_AMT {
            get {
                return ResourceManager.GetString("SUM_AMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สรุป.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier / Starff.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อความ.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accrued.
        /// </summary>
        public static string TitleAccruedList {
            get {
                return ResourceManager.GetString("TitleAccruedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงาน Accrued Summary.
        /// </summary>
        public static string TitleAccruedSummaryReportList {
            get {
                return ResourceManager.GetString("TitleAccruedSummaryReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัพโหลด Accrued.
        /// </summary>
        public static string TitleAccruedUpload {
            get {
                return ResourceManager.GetString("TitleAccruedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust and Refund Integrating Information .
        /// </summary>
        public static string TitleAdjAndRfdIntegrate {
            get {
                return ResourceManager.GetString("TitleAdjAndRfdIntegrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust and Refund Checking Last Adjust Item.
        /// </summary>
        public static string TitleAdjAndRfdMapping {
            get {
                return ResourceManager.GetString("TitleAdjAndRfdMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust and Refund Upload Data to MIS.
        /// </summary>
        public static string TitleAdjAndRfdUpload {
            get {
                return ResourceManager.GetString("TitleAdjAndRfdUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จัดการสิทธิ์การใช้งานระบบ.
        /// </summary>
        public static string TitleAppCompositeRole {
            get {
                return ResourceManager.GetString("TitleAppCompositeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดสิทธิ์ให้ผู้ใช้งาน.
        /// </summary>
        public static string TitleAssignUserRole {
            get {
                return ResourceManager.GetString("TitleAssignUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบแจ้งหนี้.
        /// </summary>
        public static string TitleInvoiceList {
            get {
                return ResourceManager.GetString("TitleInvoiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัพโหลด ใบแจ้งหนี้.
        /// </summary>
        public static string TitleInvoiceUpload {
            get {
                return ResourceManager.GetString("TitleInvoiceUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าสู่ระบบ.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Catalog.
        /// </summary>
        public static string TitlePaymentItemList {
            get {
                return ResourceManager.GetString("TitlePaymentItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Posting Timeliness.
        /// </summary>
        public static string TitlePaymentPostingTimeliness {
            get {
                return ResourceManager.GetString("TitlePaymentPostingTimeliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คัดลอก.
        /// </summary>
        public static string TitlePrefixCopy {
            get {
                return ResourceManager.GetString("TitlePrefixCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้าง.
        /// </summary>
        public static string TitlePrefixCreate {
            get {
                return ResourceManager.GetString("TitlePrefixCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบ.
        /// </summary>
        public static string TitlePrefixDelete {
            get {
                return ResourceManager.GetString("TitlePrefixDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียด.
        /// </summary>
        public static string TitlePrefixDisplay {
            get {
                return ResourceManager.GetString("TitlePrefixDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไข.
        /// </summary>
        public static string TitlePrefixEdit {
            get {
                return ResourceManager.GetString("TitlePrefixEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการ.
        /// </summary>
        public static string TitlePrefixList {
            get {
                return ResourceManager.GetString("TitlePrefixList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลทั่วไป.
        /// </summary>
        public static string TitleValueHelpSetting {
            get {
                return ResourceManager.GetString("TitleValueHelpSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL_CHARGE_AMOUNT.
        /// </summary>
        public static string TOTAL_CHARGE_AMOUNT {
            get {
                return ResourceManager.GetString("TOTAL_CHARGE_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string TRANSACTION {
            get {
                return ResourceManager.GetString("TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภท.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ข้อมูลโดย.
        /// </summary>
        public static string UploadBy {
            get {
                return ResourceManager.GetString("UploadBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ Upload ข้อมูล.
        /// </summary>
        public static string UploadDate {
            get {
                return ResourceManager.GetString("UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัพโหลดรูป.
        /// </summary>
        public static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัพโหลดรูป.
        /// </summary>
        public static string UploadPhoto1 {
            get {
                return ResourceManager.GetString("UploadPhoto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการ.
        /// </summary>
        public static string UploadType {
            get {
                return ResourceManager.GetString("UploadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรณี.
        /// </summary>
        public static string UrgentCase {
            get {
                return ResourceManager.GetString("UrgentCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การใช้งาน.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้แก้ไข.
        /// </summary>
        public static string UserLastModifies {
            get {
                return ResourceManager.GetString("UserLastModifies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHT.
        /// </summary>
        public static string WHT {
            get {
                return ResourceManager.GetString("WHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปี.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล.
        /// </summary>
        public static string ZeroRecords {
            get {
                return ResourceManager.GetString("ZeroRecords", resourceCulture);
            }
        }
    }
}
