//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Content.text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BBDEVSYS.Content.text.ValidatorMessage", typeof(ValidatorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดไฟล์เกินที่กำหนด.
        /// </summary>
        public static string attachment_file_size_exceed {
            get {
                return ResourceManager.GetString("attachment_file_size_exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทไฟล์ไม่ถูกต้อง.
        /// </summary>
        public static string attachment_invalid_type {
            get {
                return ResourceManager.GetString("attachment_invalid_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบการประมวลผลคะแนนการประเมิน {0}.
        /// </summary>
        public static string calculatescore_log_notfound {
            get {
                return ResourceManager.GetString("calculatescore_log_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการได้.
        /// </summary>
        public static string cannot_action_error {
            get {
                return ResourceManager.GetString("cannot_action_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการ{0} กรุณาทำจ่ายรายการค่าใช้จ่าย{1}ครบถ้วน บรรทัด {2}.
        /// </summary>
        public static string cannot_action_status_cancel_error {
            get {
                return ResourceManager.GetString("cannot_action_status_cancel_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการกำหนดสิทธ์ผู้ใช้ได้ เนื่องจากไม่พบ Username.
        /// </summary>
        public static string cannot_assignuserrole_action {
            get {
                return ResourceManager.GetString("cannot_assignuserrole_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถประเมินผลได้.
        /// </summary>
        public static string cannot_evaluate {
            get {
                return ResourceManager.GetString("cannot_evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถประเมินผลได้ เนื่องจากตัวแทนจำหน่ายอยู่ในสถานะปิดกิจการ.
        /// </summary>
        public static string cannot_evaluate_agent_close {
            get {
                return ResourceManager.GetString("cannot_evaluate_agent_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถประเมินผลได้ เนื่องจากผลการประเมินถูกอนุมัติแล้ว.
        /// </summary>
        public static string cannot_evaluate_approve_eva {
            get {
                return ResourceManager.GetString("cannot_evaluate_approve_eva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถประเมินผลได้ เนื่องจากเสร็จสิ้นการประเมินแล้ว.
        /// </summary>
        public static string cannot_evaluate_finish_eva {
            get {
                return ResourceManager.GetString("cannot_evaluate_finish_eva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถประเมินผลได้ เนื่องจากถูกประเมินโดยบุคคลอื่นแล้ว.
        /// </summary>
        public static string cannot_evaluate_not_initial_appraiser {
            get {
                return ResourceManager.GetString("cannot_evaluate_not_initial_appraiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถประเมินผลได้ เนื่องจากอยู่นอกช่วงเวลาการประเมิน.
        /// </summary>
        public static string cannot_evaluate_notin_period {
            get {
                return ResourceManager.GetString("cannot_evaluate_notin_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถประเมินผลได้ เนื่องจากอยู่ระหว่างการอนุมัติผลการประเมิน.
        /// </summary>
        public static string cannot_evaluate_wait_approve_eva {
            get {
                return ResourceManager.GetString("cannot_evaluate_wait_approve_eva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ {0}.
        /// </summary>
        public static string cannot_found {
            get {
                return ResourceManager.GetString("cannot_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ Action.
        /// </summary>
        public static string cannot_found_action {
            get {
                return ResourceManager.GetString("cannot_found_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบกลุ่มกิจกรรม.
        /// </summary>
        public static string cannot_found_activity {
            get {
                return ResourceManager.GetString("cannot_found_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล{0}ที่ระบุ ไม่มีในระบบ (บรรทัดที่ {1}).
        /// </summary>
        public static string cannot_found_at_data {
            get {
                return ResourceManager.GetString("cannot_found_at_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบแผนงาน {0}.
        /// </summary>
        public static string cannot_found_budgetplan {
            get {
                return ResourceManager.GetString("cannot_found_budgetplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบแผนงานย่อย {0}.
        /// </summary>
        public static string cannot_found_budgetsubplan {
            get {
                return ResourceManager.GetString("cannot_found_budgetsubplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล {0}.
        /// </summary>
        public static string cannot_found_data {
            get {
                return ResourceManager.GetString("cannot_found_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบการสร้าง Interface ใบสั่งจ่ายไปยังระบบ SAP ของเอกสาร {0}.
        /// </summary>
        public static string cannot_found_document_created {
            get {
                return ResourceManager.GetString("cannot_found_document_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลพนักงาน {0}.
        /// </summary>
        public static string cannot_found_employee {
            get {
                return ResourceManager.GetString("cannot_found_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบรายละอียดค่าใช้จ่าย.
        /// </summary>
        public static string cannot_found_expense {
            get {
                return ResourceManager.GetString("cannot_found_expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบเลขที่เอง FI Document ในใบแจ้งหนี้ {0}.
        /// </summary>
        public static string cannot_found_fi_document_in_invoice {
            get {
                return ResourceManager.GetString("cannot_found_fi_document_in_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบเลขที่ของ FI Document ใน JobGL {0}/{1}.
        /// </summary>
        public static string cannot_found_fi_document_in_jobgl {
            get {
                return ResourceManager.GetString("cannot_found_fi_document_in_jobgl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบรายละเอียดค่าใช้จ่าย.
        /// </summary>
        public static string cannot_found_gl_detail {
            get {
                return ResourceManager.GetString("cannot_found_gl_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ IO ของรหัสบัญชีที่ระบุ.
        /// </summary>
        public static string cannot_found_io_under_glAccount {
            get {
                return ResourceManager.GetString("cannot_found_io_under_glAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ Job.
        /// </summary>
        public static string cannot_found_job_for_requester {
            get {
                return ResourceManager.GetString("cannot_found_job_for_requester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกรหัสวัสดุ.
        /// </summary>
        public static string cannot_found_matCode {
            get {
                return ResourceManager.GetString("cannot_found_matCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทวัสดุ.
        /// </summary>
        public static string cannot_found_matType {
            get {
                return ResourceManager.GetString("cannot_found_matType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบแผนงาน.
        /// </summary>
        public static string cannot_found_plancode {
            get {
                return ResourceManager.GetString("cannot_found_plancode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกช่องทาง.
        /// </summary>
        public static string cannot_found_plancode_salechanneltype {
            get {
                return ResourceManager.GetString("cannot_found_plancode_salechanneltype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบแผนงานภายใต้กลุ่มกิจกรรม.
        /// </summary>
        public static string cannot_found_plancode_under_activity {
            get {
                return ResourceManager.GetString("cannot_found_plancode_under_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ Posting Date ของเอกสาร {0}.
        /// </summary>
        public static string cannot_found_posting_date {
            get {
                return ResourceManager.GetString("cannot_found_posting_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบใบปะหน้าคำขออนุมัติจ่ายชดเชยคืนตัวแทน {0}.
        /// </summary>
        public static string cannot_found_pragroup {
            get {
                return ResourceManager.GetString("cannot_found_pragroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ Process Code: {0} ในปี {1}.
        /// </summary>
        public static string cannot_found_processcode {
            get {
                return ResourceManager.GetString("cannot_found_processcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถส่งอนุมัติได้ เนื่องจากคำขอได้รับการอนุมัติแล้ว.
        /// </summary>
        public static string cannot_request_approved {
            get {
                return ResourceManager.GetString("cannot_request_approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถดำเนินการลบข้อมูลได้  เนื่องจากที่การใช้ข้อมูล{0}อยู่.
        /// </summary>
        public static string cannot_request_delete {
            get {
                return ResourceManager.GetString("cannot_request_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถส่งอนุมัติได้ เนื่องจากคำขออยู่ในขั้นตอนการพิจารณา.
        /// </summary>
        public static string cannot_request_inwfprocess {
            get {
                return ResourceManager.GetString("cannot_request_inwfprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล {0} ที่ระบุมีอยู่แล้วในระบบ.
        /// </summary>
        public static string duplicate_error {
            get {
                return ResourceManager.GetString("duplicate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบ E-mail ไม่ถูกต้อง.
        /// </summary>
        public static string email_error {
            get {
                return ResourceManager.GetString("email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปีการประเมิน {0} ประเภท {1} ยังไม่มีผลใช้งาน.
        /// </summary>
        public static string form_period_fail {
            get {
                return ResourceManager.GetString("form_period_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบปีการประเมิน {0} ประเภท {1}.
        /// </summary>
        public static string form_period_found {
            get {
                return ResourceManager.GetString("form_period_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบการประเมิน.
        /// </summary>
        public static string formperiod_notfound {
            get {
                return ResourceManager.GetString("formperiod_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ ID ของฟอร์ม.
        /// </summary>
        public static string id_not_found {
            get {
                return ResourceManager.GetString("id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ ID ของฟอร์ม.
        /// </summary>
        public static string id_not_found1 {
            get {
                return ResourceManager.GetString("id_not_found1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนที่ระบุไม่ถูกต้องเนื่องจากมีการเบิก/จองวัสดุไปแล้วจำนวน {0}.
        /// </summary>
        public static string incorrect_amount_materialstock {
            get {
                return ResourceManager.GetString("incorrect_amount_materialstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนที่ระบุไม่ถูกต้องเนื่องจากมีการเบิก/จองวัสดุไปแล้วจำนวน {0} (บรรทัดที่ {1}).
        /// </summary>
        public static string incorrect_amount_materialstock_at {
            get {
                return ResourceManager.GetString("incorrect_amount_materialstock_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล {0} ไม่ถูกต้อง.
        /// </summary>
        public static string incorrect_format {
            get {
                return ResourceManager.GetString("incorrect_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล {0} ไม่ถูกต้อง ลำดับที่ {1}.
        /// </summary>
        public static string incorrect_format_at {
            get {
                return ResourceManager.GetString("incorrect_format_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล {0} ไม่ถูกต้อง (ควรระบุ &quot;วันที่ / เดือน / ปี(ค.ศ.) &quot;  : &quot;xx / xx / xxxx&quot;  ).
        /// </summary>
        public static string incorrect_format_datetime {
            get {
                return ResourceManager.GetString("incorrect_format_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลไม่ถูกต้อง  {0} ต้องไม่น้อยกว่าที่ เบิกไปแล้ว (บรรทัดที่ {1}).
        /// </summary>
        public static string invalid_amount_error {
            get {
                return ResourceManager.GetString("invalid_amount_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบรายการตัวแทนจำหน่าย.
        /// </summary>
        public static string item_agent_notfound {
            get {
                return ResourceManager.GetString("item_agent_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล {0} ซ้ำ.
        /// </summary>
        public static string item_duplicate_error {
            get {
                return ResourceManager.GetString("item_duplicate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล {0} ที่ระบุมีอยู่แล้วในระบบ (บรรทัดที่ {1}).
        /// </summary>
        public static string item_line_duplicate_error {
            get {
                return ResourceManager.GetString("item_line_duplicate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดเพิ่มรายการ {0}.
        /// </summary>
        public static string item_listnull_error {
            get {
                return ResourceManager.GetString("item_listnull_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบรายการ.
        /// </summary>
        public static string item_not_found {
            get {
                return ResourceManager.GetString("item_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการไม่สอดคล้องกับประเภท Period {0}.
        /// </summary>
        public static string item_not_match_period_type {
            get {
                return ResourceManager.GetString("item_not_match_period_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดกรอกข้อมูล {0} ที่ {1}.
        /// </summary>
        public static string item_notempty_at_error {
            get {
                return ResourceManager.GetString("item_notempty_at_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดกรอกข้อมูล {0}  (บรรทัดที่ {1}).
        /// </summary>
        public static string item_notempty_error {
            get {
                return ResourceManager.GetString("item_notempty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดกรอกข้อมูล {0}  (ลำดับที่ {1}).
        /// </summary>
        public static string item_notempty_seq_at_error {
            get {
                return ResourceManager.GetString("item_notempty_seq_at_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล {0} ที่ระบุมีอยู่แล้วในระบบ (ลำดับที่ {1}).
        /// </summary>
        public static string item_sequence_duplicate_error {
            get {
                return ResourceManager.GetString("item_sequence_duplicate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บรรทัดที่ {0} วันที่เริ่มต้นการประเมิน ({1}) มากกว่าวันที่สิ้นสุดการประเมิน ({2}).
        /// </summary>
        public static string item_startevadate_morethan_endevadate {
            get {
                return ResourceManager.GetString("item_startevadate_morethan_endevadate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล {0} {1} ซ้ำ (บรรทัดที่ {2}).
        /// </summary>
        public static string items_line_duplicate_error {
            get {
                return ResourceManager.GetString("items_line_duplicate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; ต้องมีความยาว {MinLength} ถึง {MaxLength} ตัวอักษร.
        /// </summary>
        public static string length_error {
            get {
                return ResourceManager.GetString("length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} ต้องน้อยกว่า {0}.
        /// </summary>
        public static string lessthan_error {
            get {
                return ResourceManager.GetString("lessthan_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} ต้องน้อยกว่าหรือเท่ากับ {0}.
        /// </summary>
        public static string lessthanandequal_error {
            get {
                return ResourceManager.GetString("lessthanandequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username หรือ Password ไม่ถูกต้อง.
        /// </summary>
        public static string login_fail {
            get {
                return ResourceManager.GetString("login_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีสิทธิ์เข้าใช้งาน กรุณาติดต่อผู้ดูแลระบบ.
        /// </summary>
        public static string login_fail_no_user_role {
            get {
                return ResourceManager.GetString("login_fail_no_user_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวแทนจำหน่าย {0} ยังไม่ถูกประมวลผลคะแนน.
        /// </summary>
        public static string no_eva_score {
            get {
                return ResourceManager.GetString("no_eva_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ Form Item ในวันที่แจ้งเตือน.
        /// </summary>
        public static string note_formitem_not_found {
            get {
                return ResourceManager.GetString("note_formitem_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ Form Period ในวันที่แจ้งเตือน.
        /// </summary>
        public static string note_formperiod_not_found {
            get {
                return ResourceManager.GetString("note_formperiod_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ Period ในวันที่แจ้งเตือน.
        /// </summary>
        public static string note_period_not_found {
            get {
                return ResourceManager.GetString("note_period_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ Period Item ในวันที่แจ้งเตือน.
        /// </summary>
        public static string note_perioditem_not_found {
            get {
                return ResourceManager.GetString("note_perioditem_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดกรอกข้อมูล {PropertyName}.
        /// </summary>
        public static string notempty_error {
            get {
                return ResourceManager.GetString("notempty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดกรอกข้อมูล {0} บรรทัด {1}.
        /// </summary>
        public static string notempty_error_at {
            get {
                return ResourceManager.GetString("notempty_error_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดกรอกข้อมูล {0}.
        /// </summary>
        public static string notempty_error_in {
            get {
                return ResourceManager.GetString("notempty_error_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดกรอกข้อมูล {PropertyName}.
        /// </summary>
        public static string notnull_error {
            get {
                return ResourceManager.GetString("notnull_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บรรทัดที่ {0} วันที่เริ่มต้นและสิ้นสุดข้อมูลประเมิน ไม่สอดคล้องกับประเภทช่วงเวลา.
        /// </summary>
        public static string period_is_invalid_type {
            get {
                return ResourceManager.GetString("period_is_invalid_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ {0} และ {1} ของรายการบรรทัด {2} ไม่สอดคล้องกับปี {3}.
        /// </summary>
        public static string period_item_not_rel_year {
            get {
                return ResourceManager.GetString("period_item_not_rel_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบช่วงเวลาประเมินของปี {0} ประเภท {1} ในไตรมาส {2}.
        /// </summary>
        public static string period_not_found {
            get {
                return ResourceManager.GetString("period_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ {0} และ {1} ไม่สอดคล้องกับปี {2}.
        /// </summary>
        public static string period_not_rel_year {
            get {
                return ResourceManager.GetString("period_not_rel_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถระบุปี {0} ได้.
        /// </summary>
        public static string period_year_not_in_range {
            get {
                return ResourceManager.GetString("period_year_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลซ้ำซ้อน ไม่สามารถสร้าง Period ประเภท {0}  ในปี {1} ได้.
        /// </summary>
        public static string periodtype_exist {
            get {
                return ResourceManager.GetString("periodtype_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถสร้างการประมวลผลได้ เพราะมีการประเมินในสถานะ &quot;{0}&quot; อยู่.
        /// </summary>
        public static string process_exist {
            get {
                return ResourceManager.GetString("process_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลที่เคยประมวลผลไปแล้วจะถูกประมวลผลทับ.
        /// </summary>
        public static string process_recalculate {
            get {
                return ResourceManager.GetString("process_recalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName}.
        /// </summary>
        public static string quarter_error {
            get {
                return ResourceManager.GetString("quarter_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่เริ่มต้นมากกว่าวันที่สิ้นสุด.
        /// </summary>
        public static string start_greater_than_end {
            get {
                return ResourceManager.GetString("start_greater_than_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; สามารถมีจำนวนตัวอักษรสูงสุดได้ {MaxLength}.
        /// </summary>
        public static string string_maxlength {
            get {
                return ResourceManager.GetString("string_maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการวมได้.
        /// </summary>
        public static string summary_fail {
            get {
                return ResourceManager.GetString("summary_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีสิทธิ์เข้าใช้งาน กรุณาลองเข้าสู่ระบบอีกครั้ง.
        /// </summary>
        public static string unauthorize_error {
            get {
                return ResourceManager.GetString("unauthorize_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดตรวจสอบข้อมูลในไฟล์ Upload.
        /// </summary>
        public static string upload_file_content_error {
            get {
                return ResourceManager.GetString("upload_file_content_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดเลือกไฟล์สำหรับ Upload.
        /// </summary>
        public static string upload_file_notempty_error {
            get {
                return ResourceManager.GetString("upload_file_notempty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถดำเนินการได้.
        /// </summary>
        public static string workflow_action_error {
            get {
                return ResourceManager.GetString("workflow_action_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลผู้อนุมัติ.
        /// </summary>
        public static string workflow_no_approver_error {
            get {
                return ResourceManager.GetString("workflow_no_approver_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถส่งคำขอได้.
        /// </summary>
        public static string workflow_start_error {
            get {
                return ResourceManager.GetString("workflow_start_error", resourceCulture);
            }
        }
    }
}
