select * from FEE_ACCRUED_PLAN

select * from FEE_ACCRUED_PLAN_ITEM

select * from FEE_ACCRUED_PLAN_ITEM_SUB


select * from FEE_INVOICE_ITEM WHERE COMPANY_CODE ='TI' AND PAYMENT_ITEMS_CODE ='TITMN-CreditCardv20180801' ORDER BY INV_MONTH ,INV_YEAR

select * from FEE_INVOICE WHERE COMPANY_CODE ='TI' AND PAYMENT_ITEMS_CODE ='TITMN-CreditCardv20180801' ORDER BY INV_MONTH ,INV_YEAR

select * from FEE_INVOICE

/*
delete from FEE_ACCRUED_PLAN

delete from FEE_ACCRUED_PLAN_ITEM

delete from FEE_ACCRUED_PLAN_ITEM_SUB
*/