//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppMenu
    {
        public int ID { get; set; }
        public string MenuCode { get; set; }
        public string ResourceName { get; set; }
        public string MenuType { get; set; }
        public string ParentMenuCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string RoleForManage { get; set; }
        public string RoleForDisplay { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Area { get; set; }
        public string Icon { get; set; }
    }
}
