//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int ID { get; set; }
        public string ProcessCode { get; set; }
        public string DataKey { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string MimeType { get; set; }
        public Nullable<System.DateTime> AttachDate { get; set; }
        public string AttachBy { get; set; }
        public string SavedFileName { get; set; }
        public string FileExtension { get; set; }
        public string FileUniqueKey { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string DocumentType { get; set; }
        public string Remark { get; set; }
        public string AttachmentGroup { get; set; }
    }
}
