//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public string BAN_COMPANY { get; set; }
        public string C_COMPANY_GROUP { get; set; }
        public string contraction { get; set; }
        public string TRM_COMPANY { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_NAME_CPG { get; set; }
        public string COMPANY_NAME_EN { get; set; }
        public string NEW_PAY_POINT { get; set; }
        public string Description { get; set; }
        public byte[] Com_picture { get; set; }
        public string Address { get; set; }
        public string Road { get; set; }
        public string District { get; set; }
        public string Zone { get; set; }
        public string City { get; set; }
        public string Post_code { get; set; }
        public string Address_en { get; set; }
        public string Road_en { get; set; }
        public string District_en { get; set; }
        public string Zone_en { get; set; }
        public string City_en { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string TaxNo { get; set; }
        public string COMPANY_TYPE { get; set; }
        public string CODE_SAP { get; set; }
        public Nullable<bool> IsReconcile { get; set; }
        public bool STATUS { get; set; }
        public string Bussiness_Unit { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<bool> IsPaymentFee { get; set; }
    }
}
