//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_INVOICE_ITEM
    {
        public int ID { get; set; }
        public string INV_NO { get; set; }
        public string PAYMENT_ITEMS_FEE_ITEM { get; set; }
        public string INV_ITEM_NO { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public Nullable<decimal> TRANSACTIONS { get; set; }
        public Nullable<decimal> ACTUAL_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_CHARGE_AMOUNT { get; set; }
        public Nullable<decimal> RATE_TRANS { get; set; }
        public Nullable<decimal> RATE_AMT { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> INV_MONTH { get; set; }
        public Nullable<int> INV_YEAR { get; set; }
        public string COMPANY_CODE { get; set; }
        public string PAYMENT_ITEMS_CODE { get; set; }
    }
}
