//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_ACCRUED_PLAN_ITEM
    {
        public int ACCRUED_ITEM_ID { get; set; }
        public Nullable<int> ACCRUED_ID { get; set; }
        public string INV_NO { get; set; }
        public string PRO_NO { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public Nullable<int> ACCRUED_MONTH { get; set; }
        public Nullable<int> ACCRUED_YEAR { get; set; }
        public Nullable<int> INV_MONTH { get; set; }
        public Nullable<int> INV_YEAR { get; set; }
        public string PERIOD_ACCRUED { get; set; }
        public string COMPANY_CODE { get; set; }
        public string PAYMENT_ITEMS_CODE { get; set; }
        public Nullable<decimal> TRANSACTIONS { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> INV_AMOUNT { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CURRENCY { get; set; }
        public string REMARK_INVOICE { get; set; }
        public Nullable<bool> ISPLAN { get; set; }
        public Nullable<int> EDITION { get; set; }
        public string REMARK { get; set; }
    }
}
