//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_INVOICE
    {
        public int ID { get; set; }
        public string INV_NO { get; set; }
        public string PRO_NO { get; set; }
        public string COMPANY_CODE { get; set; }
        public Nullable<int> INV_MONTH { get; set; }
        public Nullable<int> INV_YEAR { get; set; }
        public string PAYMENT_ITEMS_CODE { get; set; }
        public string INV_REC_BY { get; set; }
        public Nullable<System.DateTime> INV_REC_DATE { get; set; }
        public string INV_APPROVED_BY { get; set; }
        public Nullable<System.DateTime> INV_APPROVED_DATE { get; set; }
        public Nullable<System.DateTime> INV_DUE_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string IS_STATUS { get; set; }
        public string CONDITION_PYM { get; set; }
        public Nullable<decimal> NET_AMOUNT { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> WHT { get; set; }
        public Nullable<decimal> DEDUCT_WHT_AMOUNT { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> INCLUDE_VAT_AMOUNT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<System.DateTime> PRO_REC_DATE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<System.DateTime> PRO_DUE_DATE { get; set; }
        public Nullable<bool> UPLOAD_TYPE { get; set; }
    }
}
