//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_RPT_EXPENSE
    {
        public int ID { get; set; }
        public string PRODUCT { get; set; }
        public Nullable<int> PERIODMONTH { get; set; }
        public Nullable<int> PERIODYEAR { get; set; }
        public string COMPANY_CODE { get; set; }
        public string PAYMENT_ITEMS_CODE { get; set; }
        public string CHANNELS { get; set; }
        public string FEE { get; set; }
        public string CHARGE { get; set; }
        public string TYPECHARGE { get; set; }
        public Nullable<decimal> NET_CHARGE { get; set; }
        public Nullable<bool> ISTYPE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string REMARK { get; set; }
    }
}
