//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_INVOICE_UPLOAD_ITEM_LOG
    {
        public int ID { get; set; }
        public int INV_UPLOAD_ID { get; set; }
        public string INV_NO { get; set; }
        public string PRO_NO { get; set; }
        public string CCT_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string INV_MONTH { get; set; }
        public string INV_YEAR { get; set; }
        public string PAYMENT_ITEMS_CODE { get; set; }
        public string INV_REC_BY { get; set; }
        public string INV_REC_DATE { get; set; }
        public string INV_APPROVED_BY { get; set; }
        public string INV_APPROVED_DATE { get; set; }
        public string INV_DUE_DATE { get; set; }
        public string IS_STATUS { get; set; }
        public string CONDITION_PYM { get; set; }
        public string NET_AMOUNT { get; set; }
        public string WHT { get; set; }
        public string DEDUCT_WHT_AMOUNT { get; set; }
        public string CURRENCY { get; set; }
        public string INCLUDE_VAT_AMOUNT { get; set; }
        public string VAT { get; set; }
        public string PRO_REC_DATE { get; set; }
        public string PAYMENT_ITEMS_FEE_ITEM { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public string TRANSACTIONS { get; set; }
        public string ACTUAL_AMOUNT { get; set; }
        public string RATE_TRANS { get; set; }
        public string RATE_AMT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string REMARK { get; set; }
        public string FUND_CODE { get; set; }
        public string GL_ACCOUNT { get; set; }
        public string FEE { get; set; }
        public string CHARGED { get; set; }
        public string CHANNELS { get; set; }
        public string TOTAL_CHARGE_AMOUNT { get; set; }
        public string DISCOUNT { get; set; }
        public string PRO_DUE_DATE { get; set; }
    }
}
