//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_ACCRUED_PLAN
    {
        public int ACCRUED_ID { get; set; }
        public Nullable<int> PERIOD_MONTH { get; set; }
        public Nullable<int> PERIOD_YEAR { get; set; }
        public string COMPANY_CODE { get; set; }
        public Nullable<decimal> TOTAL_AMT { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string REMARK { get; set; }
        public Nullable<bool> UPLOAD_TYPE { get; set; }
    }
}
