//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_ACCRUED_PLAN_UPLOAD
    {
        public int ID { get; set; }
        public Nullable<int> PERIOD_MONTH { get; set; }
        public Nullable<int> PERIOD_YEAR { get; set; }
        public string UPLOAD_BY { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE { get; set; }
        public string REMARK { get; set; }
    }
}
