//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PYMFEEEntities : DbContext
    {
        public PYMFEEEntities()
            : base("name=PYMFEEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppCompositeRole> AppCompositeRoles { get; set; }
        public virtual DbSet<AppCompositeRoleItem> AppCompositeRoleItems { get; set; }
        public virtual DbSet<AppMenu> AppMenus { get; set; }
        public virtual DbSet<AppSingleRole> AppSingleRoles { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<COMPANY> COMPANies { get; set; }
        public virtual DbSet<COST_CENTER> COST_CENTER { get; set; }
        public virtual DbSet<FEE_ACCRUED_PLAN> FEE_ACCRUED_PLAN { get; set; }
        public virtual DbSet<FEE_ACCRUED_PLAN_ITEM> FEE_ACCRUED_PLAN_ITEM { get; set; }
        public virtual DbSet<FEE_ACCRUED_PLAN_ITEM_SUB> FEE_ACCRUED_PLAN_ITEM_SUB { get; set; }
        public virtual DbSet<FEE_ACCRUED_PLAN_UPLOAD> FEE_ACCRUED_PLAN_UPLOAD { get; set; }
        public virtual DbSet<FEE_ACCRUED_PLAN_UPLOAD_ITEM_LOG> FEE_ACCRUED_PLAN_UPLOAD_ITEM_LOG { get; set; }
        public virtual DbSet<FEE_INVOICE> FEE_INVOICE { get; set; }
        public virtual DbSet<FEE_INVOICE_ITEM> FEE_INVOICE_ITEM { get; set; }
        public virtual DbSet<FEE_INVOICE_UPLOAD> FEE_INVOICE_UPLOAD { get; set; }
        public virtual DbSet<FEE_INVOICE_UPLOAD_ITEM_LOG> FEE_INVOICE_UPLOAD_ITEM_LOG { get; set; }
        public virtual DbSet<FEE_RPT_EXPENSE> FEE_RPT_EXPENSE { get; set; }
        public virtual DbSet<PAYMENT_ITEMS> PAYMENT_ITEMS { get; set; }
        public virtual DbSet<PAYMENT_ITEMS_CHAGE> PAYMENT_ITEMS_CHAGE { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<ValueHelp> ValueHelps { get; set; }
        public virtual DbSet<USER_COMPANY> USER_COMPANY { get; set; }
        public virtual DbSet<USER_LOG> USER_LOG { get; set; }
        public virtual DbSet<USER_TYPE> USER_TYPE { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    
        public virtual ObjectResult<string> Validate_User(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Validate_User", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> ValidateUser(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ValidateUser", usernameParameter, passwordParameter);
        }
    }
}
