//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_ITEMS
    {
        public int ID { get; set; }
        public string PAYMENT_ITEMS_CODE { get; set; }
        public string PAYMENT_ITEMS_NAME { get; set; }
        public string COMPANY_CODE { get; set; }
        public string LASTMODIFIED_BY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string REMARK { get; set; }
        public string Supplier { get; set; }
        public string CCT_CODE { get; set; }
        public string CHANNELS { get; set; }
        public string GL_ACCOUNT { get; set; }
        public string COST_CENTER { get; set; }
        public string FUND_CODE { get; set; }
        public Nullable<int> GROUP_SEQ_CHANNELS { get; set; }
        public Nullable<int> SEQ_CHANNELS { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public string DURATION { get; set; }
    }
}
