//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string USERPASS { get; set; }
        public string NAME { get; set; }
        public string GROUP_POSITION { get; set; }
        public Nullable<int> FNID { get; set; }
        public Nullable<byte> USER_TYPE_ID { get; set; }
        public string Business_Unit1 { get; set; }
        public string Business_Unit2 { get; set; }
        public string Business_Unit3 { get; set; }
        public string Auth { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public string INPUT_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string C_LAW { get; set; }
    }
}
