//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDEVSYS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_COMPANY
    {
        public string UCID { get; set; }
        public string USERID { get; set; }
        public string Bussiness_Unit { get; set; }
        public string BAN_COMPANY { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string create_by { get; set; }
    }
}
